services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file: .env
    volumes:
      - mongo-data:/data/db
    networks:
      - crawler-net

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8082:8081'
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - crawler-net

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    ports:
      - '6379:6379'
    networks:
      - crawler-net

networks:
  crawler-net:

volumes:
  mongo-data:
